# Generated by Django 2.2.4 on 2020-07-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200711_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Active'),
        ),
    ]
